### ISSUE TITLE
Player sprite 'hangs' on left facing walls

### ISSUE THREAD

**Issue by jdsayle** [defold/sample-pixel-line-platformer#1]
Small issue here - description of the issue and resolution follow

In palyer.collection, under the collisionobject, the third spheres X position is set as -5. At that value the player sprite can actually 'hang' onto (e.g. stop falling) most left facing walls if the user continues to hold the left arrow key while falling. 

The fix appears to be to change this value to -4, then you can fall - presumably to your video game death :upside_down_face: - as expected

**Comment by britzl** [comment]
Great, thank you for reporting. This has been fixed now!
